server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/invoicing?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.springboot.demo.entity

emp:
  empName: "zhangsan"
  empAge: 22

#配置日志
logging:
  config:
    classpath: logback-boot.xml
